keycloak_url               = "http://localhost:8081"
keycloak_username          = "admin"
keycloak_password          = "admin"
frontend_base_url          = "http://localhost:8080"
oauth2_proxy_client_id     = "plant-keeper-proxy"
oauth2_proxy_client_secret = "dev-oauth2-proxy-secret"
